#!/bin/sh
# -*- mode: sh; -*- vim: ft=sh:ts=2:sw=2:norl:et:
# Time-stamp: <2025-07-16 22:38:09 cf>
D   ${XDG_DOWNLOAD_DIR:-$HOME/Downloads}
cac ${XDG_CACHE_HOME:-$HOME/.cache}
cf  ${XDG_CONFIG_HOME:-$HOME/.config}
d   ${XDG_DOCUMENTS_DIR:-$HOME/Documents}
dt  ${XDG_DATA_HOME:-$HOME/.local/share}
h   $HOME
m   ${XDG_MUSIC_DIR:-$HOME/Music}
mn  /mnt
pp  ${XDG_PICTURES_DIR:-$HOME/Pictures}
rr  $HOME/.local/src
sc  $HOME/.local/bin
src $HOME/.local/src
vv  ${XDG_VIDEOS_DIR:-$HOME/Videos}
