#!/bin/sh
# -*- mode: sh; -*- vim: ft=sh:ts=2:sw=2:norl:et:
# Time-stamp: <2025-07-16 22:38:09 cf>
D   ~/Downloads
cac ~/.cache
cf  ~/.config
d   ~/Documents
dt  ~/.local/share
h   ~
m   ~/Music
mn  /mnt
pp  ~/Pictures
rr  ~/.local/src
sc  ~/.local/bin
vv  ~/Videos
