#!/bin/sh

f=$(realpath "$1")

[ -f "$f" ] || exit 1

if exifjpg -t "$f" 2>/dev/null; then
    b=$(exifjpg -t "$f")
else
    b=$(basename "$f")
fi

t=${b%.*}
t=$(echo "$b" | sed -e 's/_/ /g')

[ -t 1 ] && echo "$t"
# notify-send -t 1000 "[nsxiv]" "$t"

exit 0
